Human Patch
Nihlus/digos-ambassador pull request #50
Opened 2019-09-12 06:13 UTC by EvylSeven

Adds
- Human species

Fixes
- A minor error in shark-dronie

Feel free to edit this as need be.

2019-09-12 15:59 UTC, Nihlus requested changes
Looks great! Overall, it's well-written and has pretty much no syntax or formatting errors.

I would like to see some more detailed descriptions, though - in particular, descriptions should contain a mention of the bodypart's colour in some way.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Arm.yml
> +shift_message: "Soft, supple flesh begins to form over {@target}'s {@side} arm, while {@f|Their} muscular structure lessens to be more slim and average."
Change `{@f|Their}` to `{@f|their}` here.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Arm.yml
> +uniform_shift_message: "Soft skin begins to form over {@target}'s arms, while {@f|Their} muscular structure lessens to be more slim and average."
Change {@f|Their} to {@f|their} here.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Arm.yml
> +uniform_grow_message: "{@target}'s shoulders suddenly ripple and push outward, growing into a set or huamn arms. They were soon covered in smooth supple flesh, the muscles of the new appendage lookin
Make sure this is in present form - re: "They were".

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Arm.yml
> +description: "Transforms the target's arm into that of a humans'."
Write "human's" instead of "humans'". This goes for all files.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Body.yml
> +shift_message: "Smooth, human skin begins to spread over{@target}'s body before completely covering it."
Missing space between "over" and the token after it.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Body.yml
> +grow_message: "{@target} begins to grow out as they form a human body. It has smooth skin covering the entirety of it."
Looks like you forgot a word or two here? This would become "CharacterName begins to grow out[...]".

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Arm.yml
> +species: Human
The species name should be all lower case. This goes for all files.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Ear.yml
> +grow_message: "The {@side} side of {@target}'s head begins to grow outwards as a human ear quickly formed, human flesh spreading over it quickly."
Change "human ear quickly formed" to "human ear quickly forms". Same for the uniform message.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Ear.yml
> +single_description: "{@f|Their} [@side} ear is that of a humans', taking on a {@colour} coloration."
`[@side}` should be `{@side}`.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Face.yml
> +grow_message: "{@target}'s blank, featureless face reshapes itself into a that of a humans', with {@colour} skin spreading all over it as it fully forms in moments.."
Two dots at the end of this message.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Penis.yml
> +shift_message: "A ripple goes up {@target}'s shaft as it gains sensitive {@colour} flesh over the entirety of it. It began to twitch and pusle with pleasure as it finished forming, growing erect as i
This needs to be in present form.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Penis.yml
> +grow_message: "{@target}'s groin ripples and bulges as a human penis begins to grow out. The tip of it gained sensitive {@colour} flesh as the rest of it gained a similarly-colored sheath. The tip le
This needs to be in present form.

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Vagina.yml
> +shift_message: "{@target}'s slit shifts and morphs as it changes shape both internally and externally. The exterior gets partially covered with skin, the inviting walls internally becoming {@colour}
"they transforms" should be "they transform".

2019-09-12 15:59 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Vagina.yml
> +shift_message: "{@target}'s slit shifts and morphs as it changes shape both internally and externally. The exterior gets partially covered with skin, the inviting walls internally becoming {@colour}
I'd prefer if the word "slut" wasn't used here. Can you use another term?

2019-09-12 20:49 UTC, EvylSeven commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Vagina.yml
> +shift_message: "{@target}'s slit shifts and morphs as it changes shape both internally and externally. The exterior gets partially covered with skin, the inviting walls internally becoming {@colour}
Gonna remove that terminology for this specific one. Dunno what else could fit so it should be fine without it.

2019-09-12 21:00 UTC, Nihlus requested changes
Very nice, practically everything has been resolved. Just some leftovers and we're ready to merge :O

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Body.yml
> +grow_message: "{@target} torso begins to grow out as they form a human body. It has smooth {@colour+ skin covering the entirety of it."
`{@colour+` should be `{@colour}`.

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Ear.yml
> +uniform_grow_message: "Both sides of {@target}'s head begins to grow outwards as human ears quickly forms, human flesh spreading over them quickly."
"quickly form" instead of "quickly forms".

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Ear.yml
> +uniform_description: "{@f|Their} ears are those of a humans, taking on a {@colour} coloration."
"are those of a human" and another humans' you missed.

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Face.yml
> +shift_message: "{@target}'s face begins to reshape itself as their features shift to those of a human beings, with {@colour} flesh spreading all over it."
"human being"

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Face.yml
> +single_description: "{@f|Their} face is that of a humans', {@colour} skin covering it."
"human" instead of "humans'"

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Leg.yml
> +description: "Transforms the target's leg into that of a humans'."
Missed a "humans'"

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Leg.yml
> +shift_message: "{@target}'s {@side} leg is covered with human flesh from thigh to toe."
This sounds more like a description. Shifting messages should be an action that's happening. Maybe move this to the single description instead and add a colour token?

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Species.yml
> +name: Human
This should be lower case.

2019-09-12 21:00 UTC, Nihlus commented on Plugins/DIGOS.Ambassador.Plugins.Transformations/Content/Transformations/Species/human/Penis.yml
> +grow_message: "{@target}'s groin ripples and bulges as a human penis begins to grow out. The tip of it gained sensitive {@colour} flesh as the rest of it gained a similarly-colored sheath. The tip le
This should be present form. "gains" insteaf of "gained", etc.

2019-09-13 04:14 UTC, Nihlus approved these changes

2019-09-13 04:14 UTC, Nihlus commented
Awesome work. Thanks!

2019-09-13 04:14 UTC, merged